#
# * grunt-readme-generator
# * https://github.com/aponxi/grunt-readme-generator
# *
# * Copyright (c) 2013 Logan Howlett
# * Licensed under the MIT license.
# 
"use strict"
module.exports = (grunt) ->
  pkg = require("./package.json")
  # Please see the Grunt documentation for more information regarding task
  # creation: http://gruntjs.com/creating-tasks
  
  # helper functions
  make_anchor = (string) ->
    # todo: make convert a string like "Special Thanks" to "special-thanks"
    str = string.replace(/\s+/g, '-').toLowerCase()
    str = "#"+str

  back_to_top = () ->
    str = make_anchor pkg.name
    str += "-"
    result = "[Back To Top](#{str})"

  get_latest_changelog = (prefix, changelog_folder)->
    # todo: get the latest changelog file and print it to the readme

  generate_banner = (path, banner_file, output) ->
    f = path+"/"+banner_file
    unless grunt.file.exists f
      grunt.log.error "Source file \"" + f + "\" not found."
    else
      grunt.file.write output, grunt.file.read f


  generate_TOC = (files, toc_extra_links, output) ->
    grunt.file.write output, "## Jump to Section\n\n"
    for file, title of files
      link = make_anchor title
      grunt.file.write output, "* [#{title}](#{link})\n"
    # release history is generated specially since the latest-changelog is generated dynamically.
    title = "Release History"
    link = make_anchor title
    grunt.file.write output, "* [#{title}](#{link})\n"
    if toc_extra_links.length > 0
      for i in toc_extra_links
        ex = toc_extra_links[i]
        grunt.file.write output, "* #{ex}\n"
      
  generate_title = (output, travis, username) ->
    title = pkg.name
    desc = pkg.description
    grunt.file.write output, "# #{title} "

    if travis
      tra = "[![Build Status](https://secure.travis-ci.org/#{username}/#{title}.png?branch=master)](http://travis-ci.org/#{username}/#{title})"
      grunt.file.write output, "#{tra}"
    grunt.file.write output, "\n> #{desc}\n"

  append = (path, file, title, output) ->
    grunt.file.write output, "## #{title}\n"
    top = back_to_top()
    grunt.file.write output, "#{top}\n\n"
    f = path+"/"+file
    unless grunt.file.exists f
      grunt.log.error "Source file \"" + f + "\" not found."
    else
      grunt.file.write output, grunt.file.read f 

  generate_release_history = (prefix, changelog_folder) ->
    grunt.file.write output, "## Release History\n"
    top = back_to_top()
    grunt.file.write output, "#{top}\n\n"
    get_latest_changelog prefix, changelog_folder


  generate_footer = (output) ->
    date = new Date();
    str = "--------\nThis readme has been automatically generated by [readme generator](https://github.com/aponxi/grunt-readme-generator) on #{date}."
    grunt.file.write output, str


  grunt.registerMultiTask "readme_generator", "Generate Readme File", ->
    
    # Merge task-specific and/or target-specific options with these defaults.
    options = @options(
      github_username: "aponxi" # this is mainly for travis link
      output: "README.md" # where readme file should be generated in respect to Gruntfile location
      table_of_contents: on # generate table of contents
      readme_folder: "readme" # where readme partial files are located
      changelog_folder: "changelogs" # where changelog files are located
      changelog_version_prefix: "v" # under changelog folder, there are files like v0.1.0.md if the prefix is "V"
      changelog_insert_before: "legal.md" # I like my legal stuff at the bottom of the readme
      toc_extra_links: [] # Sometimes I like adding quicklinks on the top in table of contents. Table of contents (TOC) must be enabled for this option
      banner: null # I like some ascii art on the top of the readme
      has_travis: on # I use travis a lot and want to have the travis image generated on the top
    )
    
    # generate banner
    if options.banner?

      generate_banner options.readme_folder, options.banner


    # Iterate over all specified file groups.
    @files.forEach (f) ->
      
      # Concat specified files.
      
      # error on and remove invalid source files (if nonull was set).
      
      # Read file source.
      src = f.src.filter((filepath) ->
        unless grunt.file.exists(filepath)
          grunt.log.error "Source file \"" + filepath + "\" not found."
          false
        else
          true
      ).map((filepath) ->
        grunt.file.read filepath
      ).join(grunt.util.normalizelf(options.separator))
      
      # Handle options.
      src += options.punctuation
      
      # Write the destination file.
      grunt.file.write f.dest, src
      
      # Print a success message.
      grunt.log.writeln "File \"" + f.dest + "\" created."

